"""empty message

Revision ID: b398355d1ed3
Revises: cee99f2e3104
Create Date: 2019-04-08 17:18:10.482056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b398355d1ed3'
down_revision = 'cee99f2e3104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('_password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_admin'),
    sa.UniqueConstraint('email', name='uq_admin_email')
    )
    # ### end Alembic commands ###
